nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ["*"]
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    max_age: 3600

  paths:
    "^/":
      allow_origin: ["http://localhost:8080"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
